stages:
    - build
    - deploy

build_image:
    stage: build
    script:
        - docker build -t nguyentanninh123/discordbot:latest .
        - echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        - docker push nguyentanninh123/discordbot:latest

deploy_to_vps:
    stage: deploy
    script:
        - ssh -i $VPS_SSH_KEY $VPS_USERNAME@$VPS_HOST "docker pull nguyentanninh123/discordbot:latest"
        - ssh -i $VPS_SSH_KEY $VPS_USERNAME@$VPS_HOST "docker-compose down"
        - ssh -i $VPS_SSH_KEY $VPS_USERNAME@$VPS_HOST "docker-compose up -d"
