name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Build Docker image
              run: docker build -t discordbot .

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: |
            github.ref == 'refs/heads/main' &&
            contains(github.event.head_commit.message, 'deploy')
        environment: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push Docker image
              run: |
                  docker build -t nguyentanninh123/discordbot:latest .
                  docker push nguyentanninh123/discordbot:latest

            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      docker pull nguyentanninh123/discordbot:latest
                      docker stop discordbot || true
                      docker rm discordbot || true
                      docker run -d --name discordbot -p 3000:3000 nguyentanninh123/discordbot:latest
