name: Deploy Node.js App

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Debug Secrets
              run: |
                  echo "Checking if Docker Hub credentials are set..."
                  if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
                    echo "DOCKER_HUB_USERNAME is not set!"
                  else
                    echo "DOCKER_HUB_USERNAME is set."
                  fi

                  if [ -z "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
                    echo "DOCKER_HUB_TOKEN is not set!"
                  else
                    echo "DOCKER_HUB_TOKEN is set."
                  fi

                  if [ -z "${{ secrets.VPS_HOST }}" ]; then
                    echo "VPS_HOST is not set!"
                  else
                    echo "VPS_HOST is set."
                  fi

                  if [ -z "${{ secrets.VPS_USERNAME }}" ]; then
                    echo "VPS_USERNAME is not set!"
                  else
                    echo "VPS_USERNAME is set."
                  fi

                  if [ -z "${{ secrets.VPS_SSH_KEY }}" ]; then
                    echo "VPS_SSH_KEY is not set!"
                  else
                    echo "VPS_SSH_KEY is set."
                  fi

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      docker pull nguyentanninh123/discordbot:latest
                      docker-compose down
                      docker-compose up -d
