name: Deploy Node.js App

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build Docker image
              run: docker build -t your-dockerhub-username/your-repo-name:latest .

            - name: Push Docker image
              run: docker push your-dockerhub-username/your-repo-name:latest

            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      docker pull your-dockerhub-username/your-repo-name:latest
                      docker-compose down
                      docker-compose up -d
